[options]
Architecture = aarch64
SigLevel = Never

[core]
Server = http://os.archlinuxarm.org/$arch/$repo
[extra]
Server = http://os.archlinuxarm.org/$arch/$repo
[community]
Server = http://os.archlinuxarm.org/$arch/$repo
[alarm]
Server = http://os.archlinuxarm.org/$arch/$repo
[aur]
Server = http://os.archlinuxarm.org/$arch/$repo
